version: '3.8'

services:
  backend:
    build: ./devops-backend
    container_name: devops-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./my-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
