apiVersion: v1
kind: Pod
metadata:
  name: suricata
spec:
  containers:
  - name: suricata
    image: jasonish/suricata:latest
    command: ["/bin/sh"]
    args: ["-c", "tail -f /dev/null"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-dev
      mountPath: /dev
  volumes:
  - name: host-dev
    hostPath:
      path: /dev
